# permissions for end users to edit memberclusterleases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: memberclusterlease-editor-role
rules:
- apiGroups:
  - cluster.aks-caravel.mcm
  resources:
  - memberclusterleases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.aks-caravel.mcm
  resources:
  - memberclusterleases/status
  verbs:
  - get
