# permissions for end users to view memberclusterleases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: memberclusterlease-viewer-role
rules:
- apiGroups:
  - cluster.aks-caravel.mcm
  resources:
  - memberclusterleases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.aks-caravel.mcm
  resources:
  - memberclusterleases/status
  verbs:
  - get
