# permissions for end users to view memeberclusterleases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: memeberclusterlease-viewer-role
rules:
- apiGroups:
  - cluster.aks-caravel.mcm
  resources:
  - memeberclusterleases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.aks-caravel.mcm
  resources:
  - memeberclusterleases/status
  verbs:
  - get
