
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - cluster.aks-caravel.mcm
  resources:
  - managedclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.aks-caravel.mcm
  resources:
  - managedclusters/finalizers
  verbs:
  - update
- apiGroups:
  - cluster.aks-caravel.mcm
  resources:
  - managedclusters/status
  verbs:
  - get
  - patch
  - update
