apiVersion: cluster.aks-caravel.mcm/v1alpha1
kind: ManagedCluster
metadata:
  name: kind-spoke
spec:
  managedClusterClientConfigs:
    - url: localhost:52239
      secretRef: member-cluster-kind-spoke-kubeconfig
status:
  conditions:
    - type: Available
      status: true
      observedGeneration: 0
      lastTransitionTime: 2006-01-02T15:04:05Z
      reason: Testing
      message: TestingMessage

  # TODO(user): Add fields here
