apiVersion: cluster.aks-caravel.mcm/v1alpha1
kind: ManagedCluster
metadata:
  name: kind-spoke
spec:
  managedClusterClientConfigs:
    - url: localhost:52239
      secretRef: member-cluster-kind-spoke-kubeconfig
status:
  conditions:
    - type: Failed
      status: False
      observedGeneration: 1
      lastTransitionTime: 2006-01-02T15:04:05Z07:00
      reason: Testing
      message: TestingMessage

  # TODO(user): Add fields here
