apiVersion: cluster.aks-caravel.mcm/v1alpha1
kind: ManagedCluster
metadata:
  name: kind-spoke2
spec:
  managedClusterClientConfigs:
    - url: localhost:64669
      secretRef: managed-cluster-kind-spoke-kubeconfig
status:
  conditions:
    - type: Available
      status: true
      lastHeartbeatTime: '2006-01-02T15:04:05Z07:00'
      lastTransitionTime: '2006-01-02T15:04:05Z07:00'
      reason: Testing2
      message: TestingMessage2

  # TODO(user): Add fields here
